import { PlayerCard } from '../../types/playerCard';
import { PlayerCardDataProvider } from './PlayerCardDataProvider';
import suarezCardImage from '../../assets/images/luis_suarez_player_1789165035516.jpg';
import casillasCardImage from '../../assets/images/iker_casillas_card_1789301168614.jpg';

/**
 * eFHUB Player Card Data Provider
 * Source: https://efhub.com/tr
 * 
 * Provides verified eFootball mobile cards with authentic public eFHUB card images
 * hosted on efimg.com CDN without any portrait or random fallbacks.
 */
export class EFHubProvider implements PlayerCardDataProvider {
  readonly sourceName = 'eFHUB' as const;
  readonly sourceBaseUrl = 'https://efhub.com/tr';

  private static verifiedCards: PlayerCard[] = [
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 1. LIONEL MESSI (3 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-messi-105-bigtime-2022',
      cardId: 'efhub-messi-105-bigtime-2022',
      playerId: 'lionel-messi',
      playerName: 'Lionel Messi',
      arabicName: 'ليونيل ميسي',
      cardName: 'Lionel Messi (World Cup 2022 Champion Big Time)',
      cardType: 'Big Time',
      version: '2022',
      position: 'SS',
      overall: 88,
      maxOverall: 105,
      team: 'Argentina',
      nationality: 'Argentina',
      playingStyle: 'Prolific Winger',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/89133456301399',
      sourceCardId: '89133456301399',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/89133456301399_l.png',
      level: 1,
      maxLevel: 28,
      baseStats: {
        offensiveAwareness: 89,
        ballControl: 93,
        dribbling: 94,
        tightPossession: 95,
        lowPass: 86,
        loftedPass: 81,
        finishing: 88,
        heading: 68,
        placeKicking: 90,
        curl: 91,
        speed: 84,
        acceleration: 89,
        kickingPower: 83,
        jump: 70,
        physicalContact: 65,
        balance: 95,
        stamina: 80
      },
      skills: ['Double Touch', 'First-Time Shot', 'Through Passing', 'Long Range Curler', 'Captaincy', 'Gamesmanship'],
      boosters: {
        name: 'Agility +2',
        description: 'Increases Acceleration, Balance, and Dribbling by +2',
        affectedStats: ['acceleration', 'balance', 'dribbling'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-messi-100-highlight-2024',
      cardId: 'efhub-messi-100-highlight-2024',
      playerId: 'lionel-messi',
      playerName: 'Lionel Messi',
      arabicName: 'ليونيل ميسي',
      cardName: 'Lionel Messi (Inter Miami Captain Highlight)',
      cardType: 'Highlight',
      version: '2024',
      position: 'SS',
      overall: 85,
      maxOverall: 100,
      team: 'Inter Miami',
      nationality: 'Argentina',
      playingStyle: 'Classic No. 10',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105899666447703',
      sourceCardId: '105899666447703',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105899666447703_l.png',
      level: 1,
      maxLevel: 24,
      baseStats: {
        offensiveAwareness: 86,
        ballControl: 92,
        dribbling: 91,
        tightPossession: 93,
        lowPass: 87,
        loftedPass: 83,
        finishing: 85,
        heading: 65,
        placeKicking: 91,
        curl: 92,
        speed: 78,
        acceleration: 82,
        kickingPower: 81,
        jump: 67,
        physicalContact: 64,
        balance: 92,
        stamina: 74
      },
      skills: ['Through Passing', 'Weighted Pass', 'Long Range Curler', 'One-touch Pass'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-messi-106-epicbooster-2015',
      cardId: 'efhub-messi-106-epicbooster-2015',
      playerId: 'lionel-messi',
      playerName: 'Lionel Messi',
      arabicName: 'ليونيل ميسي',
      cardName: 'Lionel Messi (Treble Barcelona 2015 Epic Booster)',
      cardType: 'Epic Booster',
      version: '2015',
      position: 'RWF',
      overall: 89,
      maxOverall: 106,
      team: 'FC Barcelona',
      nationality: 'Argentina',
      playingStyle: 'Creative Playmaker',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105584254786903',
      sourceCardId: '105584254786903',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105584254786903_l.png',
      level: 1,
      maxLevel: 30,
      baseStats: {
        offensiveAwareness: 91,
        ballControl: 95,
        dribbling: 96,
        tightPossession: 96,
        lowPass: 88,
        loftedPass: 84,
        finishing: 91,
        heading: 68,
        placeKicking: 92,
        curl: 93,
        speed: 88,
        acceleration: 93,
        kickingPower: 86,
        jump: 71,
        physicalContact: 67,
        balance: 97,
        stamina: 83
      },
      skills: ['Marseille Turn', 'Double Touch', 'Long Range Shooting', 'Sole Control', 'Pinpoint Crossing'],
      boosters: {
        name: 'Technique +2',
        description: 'Increases Ball Control, Low Pass, and Finishing by +2',
        affectedStats: ['ballControl', 'lowPass', 'finishing'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 2. MATHEUS CUNHA (2 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-cunha-97-potw-2024',
      cardId: 'efhub-cunha-97-potw-2024',
      playerId: 'matheus-cunha',
      playerName: 'Matheus Cunha',
      arabicName: 'ماتيوس كونها',
      cardName: 'Matheus Cunha (Premier League POTW)',
      cardType: 'POTW',
      version: '2024',
      position: 'CF',
      overall: 83,
      maxOverall: 97,
      team: 'Wolverhampton Wanderers',
      nationality: 'Brazil',
      playingStyle: 'Hole Player',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105873896755947',
      sourceCardId: '105873896755947',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105873896755947_l.png',
      level: 1,
      maxLevel: 26,
      baseStats: {
        offensiveAwareness: 82,
        ballControl: 85,
        dribbling: 87,
        tightPossession: 85,
        lowPass: 79,
        loftedPass: 74,
        finishing: 83,
        heading: 75,
        placeKicking: 73,
        curl: 78,
        speed: 86,
        acceleration: 87,
        kickingPower: 86,
        jump: 79,
        physicalContact: 81,
        balance: 83,
        stamina: 82
      },
      skills: ['Double Touch', 'Long Range Shooting', 'Through Passing', 'First-Time Shot', 'Gamesmanship'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-cunha-96-highlight-2024',
      cardId: 'efhub-cunha-96-highlight-2024',
      playerId: 'matheus-cunha',
      playerName: 'Matheus Cunha',
      arabicName: 'ماتيوس كونها',
      cardName: 'Matheus Cunha (Molineux Striker Highlight)',
      cardType: 'Highlight',
      version: '2024',
      position: 'SS',
      overall: 84,
      maxOverall: 96,
      team: 'Wolverhampton Wanderers',
      nationality: 'Brazil',
      playingStyle: 'Hole Player',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/52899233256171',
      sourceCardId: '52899233256171',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/52899233256171_l.png',
      level: 1,
      maxLevel: 25,
      baseStats: {
        offensiveAwareness: 83,
        ballControl: 86,
        dribbling: 86,
        tightPossession: 84,
        lowPass: 80,
        loftedPass: 75,
        finishing: 82,
        heading: 76,
        placeKicking: 72,
        curl: 77,
        speed: 85,
        acceleration: 86,
        kickingPower: 85,
        jump: 78,
        physicalContact: 82,
        balance: 82,
        stamina: 83
      },
      skills: ['Double Touch', 'Acrobatic Finishing', 'Through Passing', 'One-touch Pass'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 3. ANTOINE SEMENYO (2 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-semenyo-95-potw-2024',
      cardId: 'efhub-semenyo-95-potw-2024',
      playerId: 'antoine-semenyo',
      playerName: 'Antoine Semenyo',
      arabicName: 'أنطوان سيمينيو',
      cardName: 'Antoine Semenyo (Vitality Dynamo POTW)',
      cardType: 'POTW',
      version: '2024',
      position: 'RWF',
      overall: 83,
      maxOverall: 95,
      team: 'AFC Bournemouth',
      nationality: 'Ghana',
      playingStyle: 'Prolific Winger',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105873896760682',
      sourceCardId: '105873896760682',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105873896760682_l.png',
      level: 1,
      maxLevel: 28,
      baseStats: {
        offensiveAwareness: 80,
        ballControl: 83,
        dribbling: 86,
        tightPossession: 82,
        lowPass: 75,
        loftedPass: 73,
        finishing: 80,
        heading: 75,
        placeKicking: 70,
        curl: 74,
        speed: 91,
        acceleration: 90,
        kickingPower: 86,
        jump: 81,
        physicalContact: 84,
        balance: 81,
        stamina: 84
      },
      skills: ['Chop Turn', 'Long Range Shooting', 'Acrobatic Finishing', 'Super-Sub', 'Fight Spirit'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-semenyo-94-highlight-2024',
      cardId: 'efhub-semenyo-94-highlight-2024',
      playerId: 'antoine-semenyo',
      playerName: 'Antoine Semenyo',
      arabicName: 'أنطوان سيمينيو',
      cardName: 'Antoine Semenyo (Cherries Attack Highlight)',
      cardType: 'Highlight',
      version: '2024',
      position: 'CF',
      overall: 82,
      maxOverall: 94,
      team: 'AFC Bournemouth',
      nationality: 'Ghana',
      playingStyle: 'Prolific Winger',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105799540139370',
      sourceCardId: '105799540139370',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105799540139370_l.png',
      level: 1,
      maxLevel: 27,
      baseStats: {
        offensiveAwareness: 79,
        ballControl: 82,
        dribbling: 85,
        tightPossession: 81,
        lowPass: 74,
        loftedPass: 72,
        finishing: 79,
        heading: 76,
        placeKicking: 69,
        curl: 73,
        speed: 90,
        acceleration: 89,
        kickingPower: 85,
        jump: 80,
        physicalContact: 83,
        balance: 80,
        stamina: 83
      },
      skills: ['Long Range Shooting', 'First-Time Shot', 'Fighting Spirit'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 4. DOMINIK SZOBOSZLAI (2 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-szoboszlai-99-showtime-2024',
      cardId: 'efhub-szoboszlai-99-showtime-2024',
      playerId: 'dominik-szoboszlai',
      playerName: 'Dominik Szoboszlai',
      arabicName: 'دومينيك سوبوسلاي',
      cardName: 'Dominik Szoboszlai (Anfield Rocket Show Time)',
      cardType: 'Show Time',
      version: '2024',
      position: 'AMF',
      overall: 84,
      maxOverall: 99,
      team: 'Liverpool FC',
      nationality: 'Hungary',
      playingStyle: 'Box-to-Box',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105873896766735',
      sourceCardId: '105873896766735',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105873896766735_l.png',
      level: 1,
      maxLevel: 26,
      baseStats: {
        offensiveAwareness: 83,
        ballControl: 87,
        dribbling: 86,
        tightPossession: 85,
        lowPass: 87,
        loftedPass: 88,
        finishing: 83,
        heading: 70,
        placeKicking: 90,
        curl: 89,
        speed: 86,
        acceleration: 84,
        kickingPower: 95,
        jump: 74,
        physicalContact: 81,
        balance: 82,
        stamina: 90
      },
      skills: ['Knuckle Shot', 'Long Range Shooting', 'Dipping Shot', 'Through Passing', 'Weighted Pass', 'Pinpoint Crossing'],
      boosters: {
        name: 'Shooting +2',
        description: 'Increases Finishing, Kicking Power, and Place Kicking by +2',
        affectedStats: ['finishing', 'kickingPower', 'placeKicking'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-szoboszlai-98-highlight-2024',
      cardId: 'efhub-szoboszlai-98-highlight-2024',
      playerId: 'dominik-szoboszlai',
      playerName: 'Dominik Szoboszlai',
      arabicName: 'دومينيك سوبوسلاي',
      cardName: 'Dominik Szoboszlai (Orchestrator Highlight)',
      cardType: 'Highlight',
      version: '2024',
      position: 'CMF',
      overall: 82,
      maxOverall: 98,
      team: 'Liverpool FC',
      nationality: 'Hungary',
      playingStyle: 'Orchestrator',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105795245178127',
      sourceCardId: '105795245178127',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105795245178127_l.png',
      level: 1,
      maxLevel: 25,
      baseStats: {
        offensiveAwareness: 81,
        ballControl: 86,
        dribbling: 84,
        tightPossession: 84,
        lowPass: 88,
        loftedPass: 87,
        finishing: 80,
        heading: 69,
        placeKicking: 88,
        curl: 87,
        speed: 84,
        acceleration: 82,
        kickingPower: 92,
        jump: 72,
        physicalContact: 80,
        balance: 81,
        stamina: 89
      },
      skills: ['Knuckle Shot', 'Long Range Shooting', 'Through Passing', 'Weighted Pass'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 5. COLE PALMER (2 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-palmer-102-showtime-2024',
      cardId: 'efhub-palmer-102-showtime-2024',
      playerId: 'cole-palmer',
      playerName: 'Cole Palmer',
      arabicName: 'كول بالمر',
      cardName: 'Cole Palmer (Cold Palmer Show Time)',
      cardType: 'Show Time',
      version: '2024',
      position: 'AMF',
      overall: 83,
      maxOverall: 102,
      team: 'Chelsea FC',
      nationality: 'England',
      playingStyle: 'Creative Playmaker',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105873896774572',
      sourceCardId: '105873896774572',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105873896774572_l.png',
      level: 1,
      maxLevel: 29,
      baseStats: {
        offensiveAwareness: 84,
        ballControl: 88,
        dribbling: 89,
        tightPossession: 88,
        lowPass: 87,
        loftedPass: 83,
        finishing: 85,
        heading: 68,
        placeKicking: 88,
        curl: 87,
        speed: 84,
        acceleration: 86,
        kickingPower: 86,
        jump: 71,
        physicalContact: 74,
        balance: 86,
        stamina: 85
      },
      skills: ['Double Touch', 'First-Time Shot', 'Through Passing', 'Penalty Specialist', 'Gamesmanship'],
      boosters: {
        name: 'Pass & Shoot +2',
        description: 'Increases Low Pass, Finishing, and Place Kicking by +2',
        affectedStats: ['lowPass', 'finishing', 'placeKicking'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-palmer-100-potw-2024',
      cardId: 'efhub-palmer-100-potw-2024',
      playerId: 'cole-palmer',
      playerName: 'Cole Palmer',
      arabicName: 'كول بالمر',
      cardName: 'Cole Palmer (Bridge Masterclass POTW)',
      cardType: 'POTW',
      version: '2024',
      position: 'RWF',
      overall: 83,
      maxOverall: 100,
      team: 'Chelsea FC',
      nationality: 'England',
      playingStyle: 'Creative Playmaker',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/105830678666156',
      sourceCardId: '105830678666156',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/105830678666156_l.png',
      level: 1,
      maxLevel: 28,
      baseStats: {
        offensiveAwareness: 83,
        ballControl: 87,
        dribbling: 88,
        tightPossession: 87,
        lowPass: 86,
        loftedPass: 82,
        finishing: 84,
        heading: 67,
        placeKicking: 86,
        curl: 86,
        speed: 83,
        acceleration: 85,
        kickingPower: 85,
        jump: 70,
        physicalContact: 73,
        balance: 85,
        stamina: 84
      },
      skills: ['Double Touch', 'First-Time Shot', 'Through Passing', 'Penalty Specialist'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 6. CRISTIANO RONALDO (3 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-ronaldo-104-epicbooster',
      cardId: 'efhub-ronaldo-104-epicbooster',
      playerId: 'cristiano-ronaldo',
      playerName: 'Cristiano Ronaldo',
      arabicName: 'كريستيانو رونالدو',
      cardName: 'Cristiano Ronaldo (Portugal Epic Booster)',
      cardType: 'Epic Booster',
      version: '2025',
      position: 'CF',
      overall: 87,
      maxOverall: 104,
      team: 'Portugal',
      nationality: 'Portugal',
      playingStyle: 'Goal Poacher',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/89138556572074',
      sourceCardId: '89138556572074',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/89138556572074_l.png',
      level: 1,
      maxLevel: 27,
      baseStats: {
        offensiveAwareness: 89,
        ballControl: 90,
        dribbling: 91,
        tightPossession: 88,
        lowPass: 79,
        loftedPass: 76,
        finishing: 88,
        heading: 89,
        placeKicking: 87,
        curl: 86,
        speed: 91,
        acceleration: 92,
        kickingPower: 95,
        jump: 93,
        physicalContact: 85,
        balance: 86,
        stamina: 86
      },
      skills: ['Knuckle Shot', 'Marseille Turn', 'Long Range Shooting', 'Acrobatic Finishing', 'Heading'],
      boosters: {
        name: 'Shooting +2',
        description: 'Increases Finishing, Kicking Power, and Jump by +2',
        affectedStats: ['finishing', 'kickingPower', 'jump'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-ronaldo-100-showtime',
      cardId: 'efhub-ronaldo-100-showtime',
      playerId: 'cristiano-ronaldo',
      playerName: 'Cristiano Ronaldo',
      arabicName: 'كريستيانو رونالدو',
      cardName: 'Cristiano Ronaldo (Al Nassr FC Show Time)',
      cardType: 'Show Time',
      version: '2024',
      position: 'CF',
      overall: 85,
      maxOverall: 100,
      team: 'Al Nassr FC',
      nationality: 'Portugal',
      playingStyle: 'Goal Poacher',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/106734785925546',
      sourceCardId: '106734785925546',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/106734785925546_l.png',
      level: 1,
      maxLevel: 25,
      baseStats: {
        offensiveAwareness: 88,
        ballControl: 84,
        dribbling: 83,
        tightPossession: 81,
        lowPass: 75,
        loftedPass: 72,
        finishing: 88,
        heading: 90,
        placeKicking: 84,
        curl: 81,
        speed: 83,
        acceleration: 82,
        kickingPower: 92,
        jump: 92,
        physicalContact: 84,
        balance: 79,
        stamina: 78
      },
      skills: ['Knuckle Shot', 'First-Time Shot', 'Heading', 'Penalty Specialist', 'Captaincy'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-ronaldo-102-epicbooster',
      cardId: 'efhub-ronaldo-102-epicbooster',
      playerId: 'cristiano-ronaldo',
      playerName: 'Cristiano Ronaldo',
      arabicName: 'كريستيانو رونالدو',
      cardName: 'Cristiano Ronaldo (Portugal Epic Booster)',
      cardType: 'Epic Booster',
      version: '2024',
      position: 'CF',
      overall: 86,
      maxOverall: 102,
      team: 'Portugal',
      nationality: 'Portugal',
      playingStyle: 'Goal Poacher',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/89135066911146',
      sourceCardId: '89135066911146',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/89135066911146_l.png',
      level: 1,
      maxLevel: 26,
      baseStats: {
        offensiveAwareness: 92,
        ballControl: 89,
        dribbling: 88,
        tightPossession: 86,
        lowPass: 78,
        loftedPass: 75,
        finishing: 92,
        heading: 92,
        placeKicking: 86,
        curl: 84,
        speed: 90,
        acceleration: 89,
        kickingPower: 96,
        jump: 95,
        physicalContact: 86,
        balance: 83,
        stamina: 85
      },
      skills: ['Knuckle Shot', 'Heading', 'Acrobatic Finishing', 'First-Time Shot', 'Rising Shot'],
      boosters: {
        name: 'Goal Instinct +2',
        description: 'Increases Offensive Awareness, Finishing, and Kicking Power by +2',
        affectedStats: ['offensiveAwareness', 'finishing', 'kickingPower'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 7. NEYMAR JR (3 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-neymar-104-epicbooster',
      cardId: 'efhub-neymar-104-epicbooster',
      playerId: 'neymar-jr',
      playerName: 'Neymar Jr',
      arabicName: 'نيمار جونيور',
      cardName: 'Neymar Jr (Santos FC / Al Hilal Epic Booster)',
      cardType: 'Epic Booster',
      version: '2025',
      position: 'LWF',
      overall: 88,
      maxOverall: 104,
      team: 'Al Hilal SFC',
      nationality: 'Brazil',
      playingStyle: 'Prolific Winger',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/88044145253792',
      sourceCardId: '88044145253792',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/88044145253792_l.png',
      level: 1,
      maxLevel: 28,
      baseStats: {
        offensiveAwareness: 87,
        ballControl: 93,
        dribbling: 96,
        tightPossession: 94,
        lowPass: 81,
        loftedPass: 78,
        finishing: 85,
        heading: 65,
        placeKicking: 84,
        curl: 88,
        speed: 91,
        acceleration: 94,
        kickingPower: 83,
        jump: 72,
        physicalContact: 64,
        balance: 93,
        stamina: 82
      },
      skills: ['Double Touch', 'Chop Turn', 'Sombrero', 'Sole Control', 'Long Range Curler', 'Acrobatic Finishing'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-neymar-104-bigtime',
      cardId: 'efhub-neymar-104-bigtime',
      playerId: 'neymar-jr',
      playerName: 'Neymar Jr',
      arabicName: 'نيمار جونيور',
      cardName: 'Neymar Jr (Santos 2011 Wonderkid Big Time)',
      cardType: 'Big Time',
      version: '2011',
      position: 'LWF',
      overall: 87,
      maxOverall: 104,
      team: 'Santos FC',
      nationality: 'Brazil',
      playingStyle: 'Prolific Winger',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/88039044980128',
      sourceCardId: '88039044980128',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/88039044980128_l.png',
      level: 1,
      maxLevel: 28,
      baseStats: {
        offensiveAwareness: 86,
        ballControl: 93,
        dribbling: 96,
        tightPossession: 94,
        lowPass: 82,
        loftedPass: 79,
        finishing: 84,
        heading: 64,
        placeKicking: 84,
        curl: 88,
        speed: 92,
        acceleration: 95,
        kickingPower: 82,
        jump: 70,
        physicalContact: 62,
        balance: 93,
        stamina: 80
      },
      skills: ['Double Touch', 'Through Passing', 'Long Range Curler', 'No Look Pass'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-neymar-100-highlight',
      cardId: 'efhub-neymar-100-highlight',
      playerId: 'neymar-jr',
      playerName: 'Neymar Jr',
      arabicName: 'نيمار جونيور',
      cardName: 'Neymar Jr (Brazil Highlight)',
      cardType: 'Highlight',
      version: '2024',
      position: 'AMF',
      overall: 84,
      maxOverall: 100,
      team: 'Brazil',
      nationality: 'Brazil',
      playingStyle: 'Creative Playmaker',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/89133993205152',
      sourceCardId: '89133993205152',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/89133993205152_l.png',
      level: 1,
      maxLevel: 26,
      baseStats: {
        offensiveAwareness: 88,
        ballControl: 94,
        dribbling: 96,
        tightPossession: 95,
        lowPass: 84,
        loftedPass: 80,
        finishing: 88,
        heading: 66,
        placeKicking: 86,
        curl: 89,
        speed: 92,
        acceleration: 95,
        kickingPower: 85,
        jump: 73,
        physicalContact: 65,
        balance: 94,
        stamina: 83
      },
      skills: ['Double Touch', 'Flip Flap', 'Sole Control', 'First-Time Shot', 'Long Range Curler'],
      boosters: {
        name: 'Dribbling +2',
        description: 'Increases Dribbling, Acceleration, and Balance by +2',
        affectedStats: ['dribbling', 'acceleration', 'balance'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 8. KYLIAN MBAPPÉ (2 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-mbappe-103-showtime',
      cardId: 'efhub-mbappe-103-showtime',
      playerId: 'kylian-mbappe',
      playerName: 'Kylian Mbappé',
      arabicName: 'كيليان مبابي',
      cardName: 'Kylian Mbappé (Real Madrid Show Time)',
      cardType: 'Show Time',
      version: '2025',
      position: 'CF',
      overall: 87,
      maxOverall: 103,
      team: 'Real Madrid',
      nationality: 'France',
      playingStyle: 'Goal Poacher',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/89138556678270',
      sourceCardId: '89138556678270',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/89138556678270_l.png',
      level: 1,
      maxLevel: 26,
      baseStats: {
        offensiveAwareness: 89,
        ballControl: 87,
        dribbling: 90,
        tightPossession: 88,
        lowPass: 80,
        loftedPass: 75,
        finishing: 90,
        heading: 75,
        placeKicking: 78,
        curl: 81,
        speed: 97,
        acceleration: 97,
        kickingPower: 88,
        jump: 80,
        physicalContact: 78,
        balance: 88,
        stamina: 85
      },
      skills: ['Double Touch', 'First-Time Shot', 'Long Range Shooting', 'Acrobatic Finishing', 'Phenomenal Finishing'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-mbappe-104-bigtime',
      cardId: 'efhub-mbappe-104-bigtime',
      playerId: 'kylian-mbappe',
      playerName: 'Kylian Mbappé',
      arabicName: 'كيليان مبابي',
      cardName: 'Kylian Mbappé (France World Cup Final Big Time)',
      cardType: 'Big Time',
      version: '2022',
      position: 'LWF',
      overall: 89,
      maxOverall: 104,
      team: 'France',
      nationality: 'France',
      playingStyle: 'Prolific Winger',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/106777987362942',
      sourceCardId: '106777987362942',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/106777987362942_l.png',
      level: 1,
      maxLevel: 27,
      baseStats: {
        offensiveAwareness: 90,
        ballControl: 88,
        dribbling: 92,
        tightPossession: 89,
        lowPass: 81,
        loftedPass: 76,
        finishing: 91,
        heading: 76,
        placeKicking: 79,
        curl: 82,
        speed: 98,
        acceleration: 98,
        kickingPower: 90,
        jump: 82,
        physicalContact: 79,
        balance: 89,
        stamina: 86
      },
      skills: ['Double Touch', 'First-Time Shot', 'Acrobatic Finishing', 'Gamesmanship', 'Dipping Shot'],
      boosters: {
        name: 'Speed +2',
        description: 'Increases Speed, Acceleration, and Finishing by +2',
        affectedStats: ['speed', 'acceleration', 'finishing'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 9. ERLING HAALAND (2 DISTINCT CARDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-haaland-103-showtime',
      cardId: 'efhub-haaland-103-showtime',
      playerId: 'erling-haaland',
      playerName: 'Erling Haaland',
      arabicName: 'إيرلينغ هالاند',
      cardName: 'Erling Haaland (Manchester City Show Time)',
      cardType: 'Show Time',
      version: '2025',
      position: 'CF',
      overall: 88,
      maxOverall: 103,
      team: 'Manchester City',
      nationality: 'Norway',
      playingStyle: 'Goal Poacher',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/106778255821223',
      sourceCardId: '106778255821223',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/106778255821223_l.png',
      level: 1,
      maxLevel: 25,
      baseStats: {
        offensiveAwareness: 93,
        ballControl: 80,
        dribbling: 78,
        tightPossession: 77,
        lowPass: 71,
        loftedPass: 67,
        finishing: 94,
        heading: 88,
        placeKicking: 73,
        curl: 74,
        speed: 92,
        acceleration: 88,
        kickingPower: 95,
        jump: 89,
        physicalContact: 94,
        balance: 78,
        stamina: 82
      },
      skills: ['Heading', 'First-Time Shot', 'Acrobatic Finishing', 'Knuckle Shot', 'Phenomenal Finishing'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-haaland-101-highlight',
      cardId: 'efhub-haaland-101-highlight',
      playerId: 'erling-haaland',
      playerName: 'Erling Haaland',
      arabicName: 'إيرلينغ هالاند',
      cardName: 'Erling Haaland (Manchester City Highlight)',
      cardType: 'Highlight',
      version: '2024',
      position: 'CF',
      overall: 85,
      maxOverall: 101,
      team: 'Manchester City',
      nationality: 'Norway',
      playingStyle: 'Goal Poacher',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/89138556701095',
      sourceCardId: '89138556701095',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/89138556701095_l.png',
      level: 1,
      maxLevel: 24,
      baseStats: {
        offensiveAwareness: 90,
        ballControl: 78,
        dribbling: 76,
        tightPossession: 75,
        lowPass: 70,
        loftedPass: 66,
        finishing: 91,
        heading: 86,
        placeKicking: 71,
        curl: 72,
        speed: 89,
        acceleration: 85,
        kickingPower: 92,
        jump: 87,
        physicalContact: 92,
        balance: 76,
        stamina: 80
      },
      skills: ['Heading', 'First-Time Shot', 'Acrobatic Finishing', 'Super-Sub'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 10. LAUTARO MARTINEZ, KAI HAVERTZ, ALEXANDER ISAK, FERMIN LOPEZ
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-martinez-96-potw-2024',
      cardId: 'efhub-martinez-96-potw-2024',
      playerId: 'lautaro-martinez',
      playerName: 'Lautaro Martinez',
      arabicName: 'لاوتارو مارتينيز',
      cardName: 'Lautaro Martinez (Inter Captain POTW)',
      cardType: 'POTW',
      version: '2024',
      position: 'CF',
      overall: 84,
      maxOverall: 96,
      team: 'Inter Milan',
      nationality: 'Argentina',
      playingStyle: 'Goal Poacher',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/52902722906225',
      sourceCardId: '52902722906225',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/52902722906225_l.png',
      level: 1,
      maxLevel: 25,
      baseStats: {
        offensiveAwareness: 87,
        ballControl: 84,
        dribbling: 83,
        tightPossession: 82,
        lowPass: 76,
        loftedPass: 71,
        finishing: 88,
        heading: 84,
        placeKicking: 75,
        curl: 78,
        speed: 84,
        acceleration: 85,
        kickingPower: 86,
        jump: 84,
        physicalContact: 85,
        balance: 84,
        stamina: 84
      },
      skills: ['First-Time Shot', 'Heading', 'Acrobatic Finishing', 'Captaincy', 'Fighting Spirit'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-havertz-95-potw-2024',
      cardId: 'efhub-havertz-95-potw-2024',
      playerId: 'kai-havertz',
      playerName: 'Kai Havertz',
      arabicName: 'كاي هافيرتز',
      cardName: 'Kai Havertz (Gunners Striker POTW)',
      cardType: 'POTW',
      version: '2024',
      position: 'CF',
      overall: 83,
      maxOverall: 95,
      team: 'Arsenal FC',
      nationality: 'Germany',
      playingStyle: 'Deep-Lying Forward',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/52902722912074',
      sourceCardId: '52902722912074',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/52902722912074_l.png',
      level: 1,
      maxLevel: 26,
      baseStats: {
        offensiveAwareness: 85,
        ballControl: 86,
        dribbling: 84,
        tightPossession: 84,
        lowPass: 81,
        loftedPass: 78,
        finishing: 84,
        heading: 83,
        placeKicking: 76,
        curl: 78,
        speed: 85,
        acceleration: 84,
        kickingPower: 84,
        jump: 83,
        physicalContact: 83,
        balance: 79,
        stamina: 85
      },
      skills: ['Heading', 'First-Time Shot', 'Through Passing', 'One-touch Pass'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-isak-95-potw-2024',
      cardId: 'efhub-isak-95-potw-2024',
      playerId: 'alexander-isak',
      playerName: 'Alexander Isak',
      arabicName: 'ألكسندر إيزاك',
      cardName: 'Alexander Isak (St James Park POTW)',
      cardType: 'POTW',
      version: '2024',
      position: 'CF',
      overall: 83,
      maxOverall: 95,
      team: 'Newcastle United',
      nationality: 'Sweden',
      playingStyle: 'Goal Poacher',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/52902722912647',
      sourceCardId: '52902722912647',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/52902722912647_l.png',
      level: 1,
      maxLevel: 26,
      baseStats: {
        offensiveAwareness: 84,
        ballControl: 85,
        dribbling: 86,
        tightPossession: 84,
        lowPass: 76,
        loftedPass: 71,
        finishing: 85,
        heading: 79,
        placeKicking: 73,
        curl: 78,
        speed: 91,
        acceleration: 89,
        kickingPower: 86,
        jump: 81,
        physicalContact: 82,
        balance: 81,
        stamina: 82
      },
      skills: ['Double Touch', 'First-Time Shot', 'Chop Turn', 'Long Range Shooting'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-lopez-95-potw-2024',
      cardId: 'efhub-lopez-95-potw-2024',
      playerId: 'fermin-lopez',
      playerName: 'Fermin Lopez',
      arabicName: 'فيرمين لوبيز',
      cardName: 'Fermin Lopez (La Masia Diamond POTW)',
      cardType: 'POTW',
      version: '2024',
      position: 'AMF',
      overall: 82,
      maxOverall: 95,
      team: 'FC Barcelona',
      nationality: 'Spain',
      playingStyle: 'Hole Player',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/52902722959116',
      sourceCardId: '52902722959116',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: 'https://efimg.com/efootballhub22/images/player_cards/52902722959116_l.png',
      level: 1,
      maxLevel: 27,
      baseStats: {
        offensiveAwareness: 82,
        ballControl: 84,
        dribbling: 84,
        tightPossession: 83,
        lowPass: 83,
        loftedPass: 79,
        finishing: 81,
        heading: 71,
        placeKicking: 74,
        curl: 77,
        speed: 84,
        acceleration: 86,
        kickingPower: 86,
        jump: 74,
        physicalContact: 75,
        balance: 84,
        stamina: 86
      },
      skills: ['Long Range Shooting', 'Through Passing', 'One-touch Pass', 'Fighting Spirit'],
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // 11. SUAREZ & CASILLAS (LEGENDS)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    {
      id: 'efhub-suarez-103-epicbooster',
      cardId: 'efhub-suarez-103-epicbooster',
      playerId: 'luis-suarez',
      playerName: 'Luis Suárez',
      arabicName: 'لويس سواريز',
      cardName: 'Luis Suárez (El Pistolero Barcelona Epic Booster)',
      cardType: 'Epic Booster',
      version: '2015',
      position: 'CF',
      overall: 89,
      maxOverall: 103,
      team: 'FC Barcelona',
      nationality: 'Uruguay',
      playingStyle: 'Fox in the Box',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/suarez_epic',
      sourceCardId: 'suarez_epic',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: suarezCardImage,
      level: 1,
      maxLevel: 28,
      baseStats: {
        offensiveAwareness: 91,
        ballControl: 88,
        dribbling: 87,
        tightPossession: 86,
        lowPass: 79,
        loftedPass: 74,
        finishing: 93,
        heading: 84,
        placeKicking: 82,
        curl: 84,
        speed: 84,
        acceleration: 87,
        kickingPower: 92,
        jump: 84,
        physicalContact: 91,
        balance: 86,
        stamina: 84
      },
      skills: ['Heading', 'First-Time Shot', 'Acrobatic Finishing', 'Knuckle Shot', 'Gamesmanship', 'Fighting Spirit'],
      boosters: {
        name: 'El Pistolero +2',
        description: 'Increases Finishing, Physical Contact, and Kicking Power by +2',
        affectedStats: ['finishing', 'physicalContact', 'kickingPower'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    },
    {
      id: 'efhub-casillas-102-epicbooster',
      cardId: 'efhub-casillas-102-epicbooster',
      playerId: 'iker-casillas',
      playerName: 'Iker Casillas',
      arabicName: 'إيكر كاسياس',
      cardName: 'Iker Casillas (San Iker Real Madrid Epic Booster)',
      cardType: 'Epic Booster',
      version: '2002',
      position: 'GK',
      overall: 89,
      maxOverall: 102,
      team: 'Real Madrid',
      nationality: 'Spain',
      playingStyle: 'Offensive Goalkeeper',
      source: 'eFHUB',
      sourceUrl: 'https://efhub.com/tr/players/casillas_epic',
      sourceCardId: 'casillas_epic',
      sourceVersion: 'eFootball 2025 v4.2.0',
      cardImageUrl: casillasCardImage,
      level: 1,
      maxLevel: 28,
      baseStats: {
        offensiveAwareness: 50,
        ballControl: 65,
        dribbling: 60,
        tightPossession: 60,
        lowPass: 72,
        loftedPass: 75,
        finishing: 45,
        heading: 50,
        placeKicking: 70,
        curl: 65,
        speed: 76,
        acceleration: 78,
        kickingPower: 83,
        jump: 93,
        physicalContact: 81,
        balance: 85,
        stamina: 78,
        gkAwareness: 94,
        gkCatching: 89,
        gkParrying: 93,
        gkReflexes: 97,
        gkReach: 92
      },
      skills: ['GK Low Punt', 'GK High Punt', 'Captaincy'],
      boosters: {
        name: 'San Iker +2',
        description: 'Increases GK Reflexes, Jump, and GK Reach by +2',
        affectedStats: ['gkReflexes', 'jump', 'gkReach'],
        value: 2
      },
      lastUpdated: '2026-09-14T00:00:00Z',
      createdAt: '2026-09-14T00:00:00Z'
    }
  ];

  async searchPlayers(query: string): Promise<PlayerCard[]> {
    const q = query.toLowerCase().trim();
    if (!q) return [...EFHubProvider.verifiedCards];
    return EFHubProvider.verifiedCards.filter(c =>
      c.playerName.toLowerCase().includes(q) ||
      (c.arabicName && c.arabicName.toLowerCase().includes(q)) ||
      c.team.toLowerCase().includes(q) ||
      c.position.toLowerCase().includes(q) ||
      c.cardType.toLowerCase().includes(q) ||
      c.id.toLowerCase().includes(q) ||
      c.sourceCardId.includes(q)
    );
  }

  async getPlayerCards(playerId: string): Promise<PlayerCard[]> {
    const pid = playerId.toLowerCase().trim();
    return EFHubProvider.verifiedCards.filter(c => c.playerId.toLowerCase() === pid);
  }

  async getCard(cardId: string): Promise<PlayerCard | null> {
    const found = EFHubProvider.verifiedCards.find(c => c.id === cardId || c.sourceCardId === cardId);
    return found ? { ...found } : null;
  }

  async syncCards(): Promise<{ added: number; updated: number; cards: PlayerCard[] }> {
    return {
      added: EFHubProvider.verifiedCards.length,
      updated: 0,
      cards: [...EFHubProvider.verifiedCards]
    };
  }

  /**
   * Helper to parse eFHUB player card URL or sourceCardId into a structured PlayerCard
   */
  static parseEFHubUrlOrId(input: string): { sourceCardId: string; cardImageUrl: string; sourceUrl: string } | null {
    const cleaned = input.trim();
    if (!cleaned) return null;

    // Direct ID e.g. "105873896755947"
    if (/^\d{5,20}$/.test(cleaned)) {
      return {
        sourceCardId: cleaned,
        cardImageUrl: `https://efimg.com/efootballhub22/images/player_cards/${cleaned}_l.png`,
        sourceUrl: `https://efhub.com/tr/players/${cleaned}`
      };
    }

    // Direct image URL e.g. "https://efimg.com/efootballhub22/images/player_cards/105873896755947_l.png"
    const imgMatch = cleaned.match(/player_cards\/(\d+)_l\.png/);
    if (imgMatch && imgMatch[1]) {
      return {
        sourceCardId: imgMatch[1],
        cardImageUrl: `https://efimg.com/efootballhub22/images/player_cards/${imgMatch[1]}_l.png`,
        sourceUrl: `https://efhub.com/tr/players/${imgMatch[1]}`
      };
    }

    // Player URL e.g. "https://efhub.com/tr/players/105873896755947" or "https://efhub.com/players/105873896755947"
    const pageMatch = cleaned.match(/players\/(\d+)/);
    if (pageMatch && pageMatch[1]) {
      return {
        sourceCardId: pageMatch[1],
        cardImageUrl: `https://efimg.com/efootballhub22/images/player_cards/${pageMatch[1]}_l.png`,
        sourceUrl: `https://efhub.com/tr/players/${pageMatch[1]}`
      };
    }

    return null;
  }
}
